### ISSUE TITLE
Issues with README.md

### ISSUE THREAD

**Issue by arvindsv** [srinivasupadhya/email-notifier#1]
Doesn't explain why it is not for production use (is it because it is a sample plugin?). Also, there are no releases. So, the usage info is wrong.

**Comment by srinivasupadhya** [comment]
Its not production ready since it doesn't have email settings configurable. It needs to be hard-coded. Its been tested as such, but no automation etc. Will add a few tests - make a release & remove the warning :+1:

**Comment by srinivasupadhya** [comment]
this is done now.
