### ISSUE TITLE
Notification update failed for plugin: email.notifier

### ISSUE THREAD

**Issue by agsmorodin** [srinivasupadhya/email-notifier#4]
I am using Go Version: 15.1.0(1863-42e58c22aefd03) and plugin 0.1 version.  I configured the email notifications in server configuration (hostname,user,password etc).  And notifications work fine except the fact that I see the following errors in tray and logs:

Notification update failed for plugin: email.notifier [Jul-22 15:30:46]
Interaction with plugin with id 'email.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["plugin is not configured. please provide plugin settings."]}']

**Comment by srinivasupadhya** [comment]
> I configured the email notifications in server configuration (hostname,user,password etc).

That configuration isn't for the plugin! Plugin settings is available 15.2 onwards.
